### ISSUE TITLE
psql login to pgbouncer console shows "Some psql features might not work"

### ISSUE THREAD

**Issue by yinan8128** [pgbouncer/pgbouncer#1143]
Hi,

We installed latest version postgresql and pgbouncer
postgresql 16.4 rpm     package from https://download.postgresql.org/pub/repos/yum/16/redhat/rhel-9.3-x86_64/ 
pgbouncer 1.23.1 rpm package from https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-9.3-x86_64/

Once psql login to pgbouncer console shows "Some psql features might not work" warning

```
$ psql -p 6432 pgbouncer -U pgbouncer
psql (16.4, server 1.23.1/bouncer)
WARNING: psql major version 16, server major version 1.23.
         Some psql features might not work.
Type "help" for help.

pgbouncer=#

```

**Comment by AndrewJackson2020** [comment]
I believe that this is a client side warning in psql that is meant to warn the user that they are using a different version of the psql client than the postgres server they are connecting to. In this case you are connecting to the pgbouncer console and it is returning the pgbouncer version for diagnostic purposes. I think you are safe to ignore the error.

**Comment by yinan8128** [comment]
psql version and postgresql server version are same 16.4
```
postgres=# show server_version;
 server_version
----------------
 16.4
(1 row)

postgres=#
\q
[postgres@clean-187-patronivmgr01-531330747 db_anonynomizer]$ psql --version
psql (PostgreSQL) 16.4
[postgres@clean-187-patronivmgr01-531330747 db_anonynomizer]$ psql -p 6432 pgbouncer -U pgbouncer
psql (16.4, server 1.23.1/bouncer)
WARNING: psql major version 16, server major version 1.23.
         Some psql features might not work.
Type "help" for help.

pgbouncer=#
```

**Comment by AndrewJackson2020** [comment]
Right ya that's what I'm saying. When you log into the admin console the admin console sends its version number to the psql client and psql mistakes that for the postgres version number, notices there' is a difference and throws the error. I don't think pgbouncer could make it so this warning didn't appear even if it was desirable because there is no way to predict what version of psql the end user is going to use to connect to pgbouncer.

**Comment by eulerto** [comment]
I think the WARNING message makes sense. By "psql features", it means the backslash commands and as we can see it won't work for "pgbouncer" database.

```
$ psql -U euler -p 6432 -d pgbouncer
Password for user euler: 
psql (16.4, server 1.23.1/bouncer)
WARNING: psql major version 16, server major version 1.23.
         Some psql features might not work.
Type "help" for help.

pgbouncer=# \du
ERROR:  invalid command 'SELECT r.rolname, r.rolsuper, r.rolinherit,
  r.rolcreaterole, r.rolcreatedb, r.rolcanlogin,
  r.rolconnlimit, r.rolvaliduntil
, r.rolreplication
FROM pg_catalog.pg_roles r
WHERE r.rolname !~ '^pg_'
ORDER BY 1;', use SHOW HELP;

```

**Comment by yinan8128** [comment]
Hi @AndrewJackson2020 

We also used pgbouncer 1.14.0 in postgresql 11 and pgbouncer 1.17.0 in postgresql 14, but no this warning

1. pgbouncer 1.14.0 in postgresql 11
```
$ psql -p 6432 pgbouncer -U pgbouncer
psql (11.18, server 1.14.0/bouncer)
Type "help" for help.

pgbouncer=#
```

2. pgbouncer 1.17.0 in postgresql 14
```
$ psql -p 6432 pgbouncer -U pgbouncer
psql (14.6, server 1.17.0/bouncer)
Type "help" for help.

pgbouncer=#
```

**Comment by eulerto** [comment]
That's because Postgres 15 modified psql to remove support for Postgres 9.2 (see postgres/postgres@cf0cab868aa4758b7eec5f9412f2ec74acda7f45). Since PgBouncer uses its own version as SERVER_VERSION_NUM (12301) and it will be less then version 9.2 (90200), it will print this WARNING from now on (until PgBouncer reaches version 9.2 or whatever minimal version psql decides to support). Check the psql code: https://github.com/postgres/postgres/blob/52f3de874bbeaf16b3ae2efb505c1117be8355cc/src/bin/psql/command.c#L3850-L3862
