### ISSUE TITLE
Is there a pkt_buf value that is too low?

### ISSUE THREAD

**Issue by cosgroveb** [pgbouncer/pgbouncer#1170]
Hey, sorry for the vague issue that I'm opening here but I noticed recently that our pkt_buf value is set (somewhat unintentionally) to an ancient value that was the default until 1.7, I think? We have 2046. I'm taking the explicit setting out and relying on the default but it made me wonder:

Can you foresee operational issues for anyone with such a weirdly low value on a low-level setting like this? With the default increased, is there a value that's too low and should consequently be documented or validated in config loading?

**Comment by JelteF** [comment]
2046 should probably be fine. In the end this setting is mostly to control a tradeoff between CPU usage and memory usage.

If you go extremely low, e.g. 10, I think you'll likely run into issues though. Because some code probably assumes that certain small messages always fit into the buffer. I don't know where the limit is, and it might very well depend on the workload. i.e. you'd get issues like this: https://github.com/pgbouncer/pgbouncer/issues/1056 But mostly your perf would be really bad.

**Comment by cosgroveb** [comment]
Thanks for the explanation. We have exerienced some unexplained very infrequent crashes (that seem to correspond with high throughput environments and ONLY when the bouncer is using TLS connecting to the server) so I thought us explicitly setting this so low was very odd and I thought I should ask. 

I'll open a new issue when, say, I have a coredump to share. It's been a pain to gather with our k8s setup and I also need to put out a build with debug symbols so it's taking time to get the data I need.  Thanks for fielding this shot in the dark!
