### ISSUE TITLE
SIGQUIT in 1.23.* still Not Compatible with old SIGTERM

### ISSUE THREAD

**Issue by chobostar** [pgbouncer/pgbouncer#1198]
### Issue Summary
The behavior of exit codes for signals has changed in pgbouncer version 1.23.*, causing incompatibility issues, particularly in systemd units configured to restart pgbouncer on failure.

### Detail
Old exit code was `1`:
https://github.com/pgbouncer/pgbouncer/blob/pgbouncer_1_16_1/src/main.c#L438-L443
```
static void handle_sigterm(evutil_socket_t sock, short flags, void *arg)
{
	log_info("got SIGTERM, fast exit");
	/* pidfile cleanup happens via atexit() */
	exit(1);
}
```

New exit code is `0`:
https://github.com/pgbouncer/pgbouncer/blob/pgbouncer_1_23_1/src/main.c#L530-L535
```
static void handle_sigquit(evutil_socket_t sock, short flags, void *arg)
{
	log_info("got SIGQUIT, fast exit");
	/* pidfile cleanup happens via atexit() */
	exit(0);
}
```

### Problem Description

Our `systemd` configuration relies on the `on-failure` restart mode, which triggers a restart when a service exits with a non-zero status. We use `SIGTERM` for stopping pgbouncer due to utilizing the postgres user via SSH, and integration with repmgr failover scripts.

With the new `pgbouncer` behavior,  `SIGQUIT` results in an exit code of `0`, causing `systemd` to not automatically restart `pgbouncer` as it no longer views the exit as a failure

The current documentation states:
> If you relied on the old behaviour of SIGTERM in your Dockerfile or Systemd service file you should now use SIGQUIT.

However, this statement is not entirely accurate due to the new behavior of exiting with code `0` upon `SIGQUIT`.

### Request
Could you consider setting `exit(1)` for `SIGQUIT` to maintain compatibility with the previous behavior ?

**Comment by JelteF** [comment]
1. I didn't realized I changed this. Otherwise I would have noted it in the release notes.
2. The new behavior seems more sensible: You asked pgbouncer to quit, and pgbouncer quit. So that seems like a successful exit to me.
3. Why are you not using `systemctl restart pgbouncer` to restart pgbouncer? Using `on-failure` this way to make `SIGTERM` effectively become a "restart signal" seems a pretty convoluted way of restarting.

**Comment by JelteF** [comment]
> However, this behavior is not transparent or safe for clients.

Sure but that's exactly what you asked for by sending it the signal. A non-zero exit code imo means something went wrong. And in this case everything went correct, because the program did exactly what you asked of it. For instance a non-zero exit code would be expected on a segfault or an assert failure.   

>     3. `systemctl restart pgbouncer` - because we are not using the root user to reconfigure pgbouncer. 

If you add something like the following to the `/etc/sudoers` file you should be able to use `sudo systemctl restart pgbouncer` from the non-root user:
```sudo
youruser ALL=(root) NOPASSWD: /path/to/systemctl restart pgbouncer
```

Another option would be to use `Restart=always` instead of `Restart=on-failure`

**Comment by chobostar** [comment]
Thanks for providing the feedback.

Yeah, an exit code of 0 is more common for modern applications. Removing the use of exit code 1 is breaking change, but a severe one.

I hope the workaround you provided will be helpful to users who encounter this issue.
