### ISSUE TITLE
make unistall pgbouncer

### ISSUE THREAD

**Issue by mohitdubey23** [pgbouncer/pgbouncer#135]
while doing make install I am getting no such rule error...how can I uninstall pgbouncer sompletely from my server

**Comment by eulerto** [comment]
There is no such rule (uninstall). However, you could remove file by file to uninstall pgbouncer (7 files are installed). Installing pgbouncer adds the following files:

```
$ make install
     INSTALL  pgbouncer /tmp/test/bin
     INSTALL  README.rst /tmp/test/share/doc/pgbouncer
     INSTALL  NEWS.rst /tmp/test/share/doc/pgbouncer
     INSTALL  etc/pgbouncer.ini /tmp/test/share/doc/pgbouncer
     INSTALL  etc/userlist.txt /tmp/test/share/doc/pgbouncer
     INSTALL  doc/pgbouncer.1 /tmp/test/share/man/man1
     INSTALL  doc/pgbouncer.5 /tmp/test/share/man/man5
```

Remove them and you uninstall pgbouncer.

It seems a useful target but it is not. Packagers prefer to do it outside autoconf execution because they can choose carefully what they are removing/keeping. Also, autoconf documentation [1] have the same recomendation.

[1] https://www.sourceware.org/autobook/autobook/autobook_79.html

**Comment by markokr** [comment]
Its not very useful indeed, but at same time it makes sense to makefile have 'uninstall' that just does reverse of install.  Which antimake.mk now has. So it should work in master.
