### ISSUE TITLE
pgbouncer read-only transaction issues

### ISSUE THREAD

**Issue by bgabler** [pgbouncer/pgbouncer#176]
When attempting a query through pgbouncer we start to get:
``
(pq: cannot execute UPDATE in a read-only transaction)
``

We currently have pgbouncer deployed in front of a master/slave 9.6 setup on docker.

Everything seems to work great but then out of nowhere we're getting back that the database is in read-only when in fact it's not.

If we connect directly to the master, it's working perfectly fine.

We're not showing anything in the pgbouncer logs other than (over and over again)
```
2017-01-13 14:05:28.352 10 LOG Stats: 0 req/s, in 59 b/s, out 96 b/s,query 2000 us
2017-01-13 14:05:34.569 10 LOG C-0xb327e8: master/XXXXXX@10.4.53.16:39590 closing because: client close request (age=10)
2017-01-13 14:05:34.583 10 LOG C-0xb327e8: master/XXXXXX@10.4.53.16:39620 login attempt: db=master user=XXXXXXX tls=no
```

Config as follows:
```
[databases]
master = host=XXXXXXXX port=5432 dbname=XXXXXX

[pgbouncer]
listen_port = 5432
listen_addr = *
user = daemon
auth_type = md5
auth_file = /pgconf/users.txt
logfile = /tmp/pgbouncer.log
pidfile = /tmp/pgbouncer.pid
admin_users = admin
ignore_startup_parameters = extra_float_digits
```

If we restart pgbouncer, everything works perfectly fine.

**Comment by oxydo** [comment]
At a first glance I thought you were using transaction pool_mode. But you are obviously using pgbouncer in session pool_mode (it's the default value when not explicitly set).

I just ran into the same problem where clients encounter errors like "cannot execute .. in a read-only transaction". It turned out that my app sometimes starts read-only transactions via 'SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY' that mark the whole connection as read-only and therefore clients reusing that connection later get the same error.

If you are not using the transaction pool_mode, you're probably facing another issue. I just wanted to share that here because it took me some time to figure out my problem.

**Comment by markokr** [comment]
In session pooling mode, DISCARD ALL is supposed to reset session state.  If it does not, then its bug of Postgres. Please report to them.

**Comment by bgabler** [comment]
@markokr Thanks bud

**Comment by mkurz** [comment]
@bgabler What was the problem in the end? How did you solve it?

**Comment by xuhongmeng** [comment]
> At a first glance I thought you were using transaction pool_mode. But you are obviously using pgbouncer in session pool_mode (it's the default value when not explicitly set).
> 
> I just ran into the same problem where clients encounter errors like "cannot execute .. in a read-only transaction". It turned out that my app sometimes starts read-only transactions via 'SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY' that mark the whole connection as read-only and therefore clients reusing that connection later get the same error.
> 
> If you are not using the transaction pool_mode, you're probably facing another issue. I just wanted to share that here because it took me some time to figure out my problem.

How did you do that？
