### ISSUE TITLE
max_pool_size <> default_pool_size ?..

### ISSUE THREAD

**Issue by VaoTsun** [pgbouncer/pgbouncer#190]
Does max_pool_size in formula 

> max_client_conn + (max_pool_size * total_databases * total_users)  in [manual](https://pgbouncer.github.io/config.html) actually mean default_pool_size?.. 
It logically does, but then why not using default_pool_size in that formula instead?..

http://stackoverflow.com/q/38235658/5315974

**Comment by eulerto** [comment]
@VaoTsun max_pool_size is not a pgBouncer parameter. It is just a variable used in the maximum-file-descriptors formula. Maybe use should mention this information. In fact, max_pool_size is max(pool_size, default_pool_size).

**Comment by VaoTsun** [comment]
Thanks for respond! 
I would say it is definitely worth to change 

> max_client_conn + (max_pool_size * total_databases * total_users)

to
>  max_client_conn + (max(pool_size, default_pool_size) * total_databases * total_users)

in docs and put some comments. Otherwise using variable is pointless (if you don't understand what it stands for)

**Comment by eulerto** [comment]
As I said, it is just a formula. I agree that is confusing (it seems similar to *pool_size), however, total_databases and total_users can confuse users too. I'm afraid we don't accurately express the concept in a formula because pool_size is per-database entry and we need to sum all database entries as max(pool_size, default_pool_size) * total_users and then multiply the result with total_databases.

**Comment by qdw** [comment]
Thank you so much for explaining this!

Why is the formula

max_client_conn + (max(pool_size, default_pool_size) * total_databases * total_users)

Rather than

max_client_conn + (min(pool_size, default_pool_size) * total_databases * total_users)

I would expect that if I set a per-DB pool_size smaller than default_pool_size, then that pool_size would constrain the number of connections and hence file descriptors.
