### ISSUE TITLE
PGBouncer swapping query parameters in txn pooling mode

### ISSUE THREAD

**Issue by quixoten** [pgbouncer/pgbouncer#203]
I'm seeing behavior that suggests pgbouncer is not properly tracking queries and their associated parameters. PostgreSQL is seeing the following query:

```
postgresql-Mon.log:2017-04-24 18:41:43 UTC [32449-10/502835-1885] vault-rw@vault_sandbox LOG:  execute <unnamed>: DELETE FROM "vault_kv_store" WHERE path = $1 AND key = $2
postgresql-Mon.log-2017-04-24 18:41:43 UTC [32449-10/502835-1886] vault-rw@vault_sandbox DETAIL:  parameters: $1 = '/core/', $2 = 'keyring'
```

however, when tracking the same time period through pgdump, all of the deletes look like this:

```
12:39:17.029305 IP 10.47.34.66.35546 > 10.47.33.194.6432: Flags [P.], seq 3674941113:3674941191, ack 96577772, win 3258, options [nop,nop,TS val 1793160414 ecr 1961402795], length 78
E..._J@.@...
/"B
/!.... ..&.........X......
j.t.t...P...A.DELETE FROM "vault_kv_store" WHERE path = $1 AND key = $2...D....S.S....
12:39:17.030994 IP 10.47.34.66.35546 > 10.47.33.194.6432: Flags [.], ack 32, win 3258, options [nop,nop,TS val 1793160414 ecr 1961538406], length 0
E..4_K@.@...
/"B
/!.... ..'.........X......
j.t.t..f
12:39:17.031125 IP 10.47.34.66.35546 > 10.47.33.194.6432: Flags [P.], seq 78:163, ack 32, win 3258, options [nop,nop,TS val 1793160414 ecr 1961538406], length 85
E..._L@.@...
/"B
/!.... ..'.........X......
j.t.t..fB...E........../core/leader/...$65c68189-8852-cd3b-3fff-9da9ba1278c4..E...      .....S....
```

There is no sequence in the tcpdump logs of a packet containing a `DELETE FROM` followed by a packet containing `/core/` and `keyring`; however, there are `SELECT` queries with `/core/` and `keyring` parameters happening at the same time as the `DELETE` queries.

Hoping to get some additional insight on this issue. As far as I can tell, pgbouncer is not properly tracking the parameters. This might be due to the parameters always coming in a separate packet, rather than the same packet that contains the query? I'm not that familiar with the postgresql wire protocol.

**Comment by quixoten** [comment]
Under the hood, it looks like a "parameterized statement" is just another name for an unnamed prepared statement. It seems likely that pgbouncer doesn't support unnamed prepared statements in transaction pooling mode by design. Is this something that could be supported?

**Comment by eulerto** [comment]
@quixoten it is not supported. It is a hard task because a PREPAREd plan is stored in the backend side (postgres connection memory). In transaction polling mode, a client can use different postgres connections during the connection lifetime. Because of that, if pgBouncer doesn't serve the same connection, it should replan the query (slower execution) or have a mechanism to pin that client on that connection (same as session mode). I'm afraid both options aren't good enough and also involve only pgBouncer. However, if postgres change the mechanism of storing PREPAREd plans (global instead of local), pgBouncer and other postgres connection pollers could benefit of that (Have in mind, it is not a simple task and is on the Postgres TODO for a long time [1][2]).

[1] https://wiki.postgresql.org/wiki/Todo#Cache_Usage
[2] https://www.postgresql.org/message-id/op.t9ggb3wacigqcu%40apollo13.peufeu.com

**Comment by quixoten** [comment]
Thanks for the info!
