### ISSUE TITLE
query_timeout limits the whole transaction execution time, not a query execution time

### ISSUE THREAD

**Issue by dimikot** [pgbouncer/pgbouncer#22]
This is either a documentation bug OR a pgbouncer bug. Which one?

My artificial pgbouncer.ini:

...
pool_mode = session
query_timeout = 2        <-- explicitly set to a low value to reproduce
...

I noticed that this query_timeout also limits the whole transaction execution time, not a single query time. So if I begin a transaction and wait for e.g. 5 seconds, the next query in the transaction will immediately fail with "query timeout" message. 

Steps to reproduce:

$ cat 2_test.php
<?php
$connStr = "host='127.0.0.1' port='6432' dbname='db' user='...' password='...'";
$conn = pg_connect($connStr);
if (!@pg_query($conn, $sql = "select 0"))
    die("SQL: $sql\n" . pg_last_error($conn) . "\n");
if (!@pg_query($conn, $sql = "begin"))      // <-- try commenting out this "if"
    die("SQL: $sql\n" . pg_last_error($conn) . "\n");
sleep(5);
if (!@pg_query($conn, $sql = "select 1"))
    die("SQL: $sql\n" . pg_last_error($conn) . "\n");

$ php 2_test.php
SQL: select 1
ERROR:  query timeout
ERROR:  query timeout

If you remove "begin" query, everything starts to work fine.

Why? The docs says nothing about transactions, it says only: "Server connection is closed if query does not return in this time".

Also, here are some logs:

$ cat /var/log/pgbouncer
...
...@x.x.x.x:5432 closing because: query timeout (age=2)
...@127.0.0.1:59779 closing because: query timeout (age=2)
...@127.0.0.1:59779 Pooler Error: query timeout
...

$ cat trace.log   # created by pg_trace('trace.log', 'w', $conn);
https://gist.github.com/DmitryKoterov/17fd856dd24bbf987779  <!-- see this

$ pgbouncer --version
pgbouncer version 1.5.4 (compiled by root@pgdgbuild.dus.dg-i.net at 2013-03-22 14:46:07)

**Comment by debussyman** [comment]
This is also true for idle_transaction_timeout. The age of the transaction is measured from the time the request started, instead of how long the actual transaction has been idle (https://github.com/pgbouncer/pgbouncer/blob/28adb8d04efc62215cdfba534eeffbb6d1b11e8c/src/janitor.c#L470)

This means that if you have a query that takes longer than the configured timeout, the transaction will be canceled, often before you can extract the result set on the application side.

I consider this a bug. Any chance this will be amended?
