### ISSUE TITLE
Native Prometheus exporter support

### ISSUE THREAD

**Issue by stanhu** [pgbouncer/pgbouncer#289]
We're looking at instrumenting pgbouncer with Prometheus instead of relying on third-party exporters. Would you accept a PR to add native Prometheus support?

**Comment by SuperQ** [comment]
For context, this would involve adding a micro embedded http server that would allow access to the data from `show stats`, and similar.

The format itself is a simple read-only text[0] representation of the data.

There are two current exporters, both have issues that we would like to eliminate by having native instrumentation.

https://github.com/spreaker/prometheus-pgbouncer-exporter 
https://github.com/larseen/pgbouncer_exporter/

[0]: https://prometheus.io/docs/instrumenting/exposition_formats/

**Comment by vthriller** [comment]
> both have issues that we would like to eliminate by having native instrumentation

I'm curious: what issues are you talking about here?

**Comment by SuperQ** [comment]
The `spreaker` exporter in Python, which we would prefer to not need for our packaging sanity.

The `larseen` exporter is better, but has a number of naming/metrics best practices problems.  Since I posted the comment, we created a [fork](https://github.com/stanhu/pgbouncer_exporter/) with a number of fixes.  I will try and get this sent upstream.

The main reason we would like native metrics support is it simplifies deploys by eliminating the need for a 3rd party metrics tool.

**Comment by petere** [comment]
I don't see us adding an HTTP server into PgBouncer.

**Comment by PJMODOS** [comment]
Not to mention I don't think we want to integrate into one specific monitoring solution (unless it's couple lines of code, which HTTP server definitely isn't). I think the time is better spent pushing forwards projects like https://github.com/influxdata/telegraf/pull/3918 TBH.

**Comment by eakraly** [comment]
How about https://github.com/launchdarkly/c-client? Now should be pretty straightforward.

**Comment by halcyondude** [comment]
@PJMODOS given what's happened in the past 18 months since this issue was closed (k8s adoption, OpenMetrics, widespread adoption of Prometheus, CNCF, Cortex, ..., etc), IMHO this should be revisited.

We would greatly prefer a native integration vs. relying on an exporter, perhaps feature flags could allow for supporting OpenMetrics in a selective "opt-in" way.

**Comment by SuperQ** [comment]
There's a new [Prometheus C library](https://github.com/digitalocean/prometheus-client-c) that might be worth looking at.

**Comment by MSDehghan** [comment]
Any updates on this?
