### ISSUE TITLE
Unable to PAUSE the server with pool_mode=session

### ISSUE THREAD

**Issue by saurabhnanda** [pgbouncer/pgbouncer#369]
I'm trying to setup a fairly simple pgbouncer installation, which consists of pgbouncer proxying connections between various app-servers (Rails & Haskell) and postgres.

- pgbouncer is listening on port 5432 and proxying connects via unix domain socket to port 5433
- postgres is listening on port 5433

When I connect to the pgbouncer admin console on port 5432 and issue the `PAUSE` or `PAUSE mydb` command, the command never completes with `pool_mode = session`. If I change to `pool_mode = transaction` it works.

Is this expected behaviour?

**Comment by saurabhnanda** [comment]
Here's what the docs say about the `PAUSE` command:

> PgBouncer tries to disconnect from all servers, first waiting for all queries to complete. The command will not return before all queries are finished.

What is considered as a "query" when `pool_mode=session`?

**Comment by jcoleman** [comment]
While I'm not a contributor to pgbouncer, here's my understanding:

The point of transaction pooling separate client (from your app to pgbouncer) and backend (from pgbouncer to Postgres) connections so that they're no longer 1:1. The point of session pooling is to retain the semantics of a 1:1 mapping while still providing some of the pooling/startup time/etc. benefits of long-running backend connections.

To put it another way: session pooling guarantees that your client connections maps 1:1 with a backend connection for as long as that client connection is open. That guarantees transparency -- for example, prepared statements work. But that transparency comes at a cost: you can't stop a backend connection until the client disconnects. If `PAUSE` paused session-pooled client connections, then you'd be able to swap out the backend connections, and that would break the transparency guarantees of session pooling.

I believe that `PAUSE` with session pooling still has an effect, but only applies when the client connection ends.

**Comment by PJMODOS** [comment]
it's pretty much how @jcoleman described it, if you want to kick all clients that are connected but let transactions finish you can use `RECONNECT` command along with `server_fast_close = on` configuration (is different session than the `PAUSE`).
