### ISSUE TITLE
feature request: change ssl parameters with reload

### ISSUE THREAD

**Issue by dobrotaf** [pgbouncer/pgbouncer#380]
Hello there,
i wonder if it is possible and how hard to implement it would be to make ssl parameters changeable uppon SIGHUP (similiar as this feature in pg10 https://paquier.xyz/postgresql-2/postgres-10-ssl-reload/)?
This became real issue once pgbouncer is deployed with ssl certificates as there is no possible way to renew certificate without killing all connections.

Thank you.

**Comment by petere** [comment]
I think it would be possible, and it would be hard. ;-)

**Comment by MannerMan** [comment]
This would make certificate administration in pgbouncer much easier :+1:

**Comment by JelteF** [comment]
@petere I took a look at the code and it seems fairly straightforward to support this. Mainly rerun `sbuf_tls_setup` at config reload (and allow changing the tls settings on reload). Already existing connections should not be affected by this, since they get assigned an ssl context when the handshake starts and OpenSSL keeps a reference count on `SSL_CTX`. I might open a PR to do this in the near future after I actually implement this and tested that it works.

Do you know anything I'm overlooking here? i.e. why do you think it would be hard?

**Comment by JelteF** [comment]
This can be closed now that #550 is merged.
