### ISSUE TITLE
invalid command 'SHOW ALL', use SHOW HELP;

### ISSUE THREAD

**Issue by and-semakin** [pgbouncer/pgbouncer#409]
I try to connect to pgbouncer admin panel using awesome [`pgcli`](https://github.com/dbcli/pgcli), but the result is:

```
invalid command 'SHOW ALL', use SHOW HELP;
```
and then `pgcli` exits with error code.

I can successfully connect to another database (not `pgbouncer` panel, but actual database in PostgreSQL) using `pgcli` through `pgbouncer`.

pgbouncer version:
```
pgbouncer=# SHOW VERSION;
NOTICE:  pgbouncer version 1.9.0
SHOW
```

pgcli version:
```
$ pgcli --version
Version: 2.0.2
```

**Comment by petere** [comment]
pgcli automatically executes a `SHOW ALL` on each new connection to capture server-side settings (see https://github.com/dbcli/pgcli/blob/master/pgcli/pgexecute.py#L294). It should be taught not to do that when it connects to pgbouncer. (It's also kind of wrong in general, since the server automatically sends interesting parameters to the client after startup, so running `SHOW ALL` again just to get the `is_superuser` flag is wasteful.) Please report an issue there.

**Comment by petere** [comment]
> We're checking for superuser status to change the prompt of the pgcli repl. So it is a fairly non-critical use case. Would you recommend a different way to get this information?

psql gets this flag using `PQparameterStatus(pset.db, "is_superuser");` without an extra round trip. You need to check how you can get that in your Python library, but the information is already there sitting in libpq.

**Comment by and-semakin** [comment]
After `pgbouncer` devs fixed issue with `SHOW VERSION` query (thanks @j-bennet and @amjith), another issue occurred:

```
$ pgcli -h localhost -p 6432 -u cs pgbouncer
Password for cs: 
invalid command 'select pg_backend_pid()', use SHOW HELP;
```

It seems like `pgbouncer` database lacks some functions which `pgcli` expects any postgres database to have :man_shrugging:

**Comment by Melkij** [comment]
pgbouncer itself does not support SQL at all. Even `select 1`.
You need ask pgcli team, not pgbouncer.

**Comment by j-bennet** [comment]
Yes, we're tracking it in https://github.com/dbcli/pgcli/issues/1093.
