### ISSUE TITLE
pgbouncer rejecting "forbidden" commands

### ISSUE THREAD

**Issue by takeda** [pgbouncer/pgbouncer#417]
Would it be feasible to provide a setting where pgbouncer in a transaction or statement mode would simply reject commands that are not allowed (I mean the commands listed in the table on https://pgbouncer.github.io/features.html)?

For example not allowing `LISTEN` or `NOTIFY` or `SET` etc but allowing for example `SET LOCAL` which is on transaction level etc.

Basically I run into an issue, where an application was using a pgbouncer in transaction mode and it seemed to work fine. The pgbouncer was running on the same host as the application of the same type (all connections are sent from the same application, it just has different roles, some are web requests, some are workers etc).

To reduce number of connections to the database I separated a pgbouncer from the hosts and made it as a proxy service. This dropped database connections as expected and had some performance improvement, but it also uncovered an issue with our application.

The developers for example were happily using `SET statement_timeout = ...` and it kind of worked, because the same application role was typically using the same value for all queries it issued. Once a central pgbouncer service was created and different roles started to share the same pool we learned that of course calling `SET ...` often had no effect, and what's worse it actually would affect something else.

Of course there's already an option (`server_reset_query_always`) to reset the connection, to at least solve the side effects, but it also reduces performance. If pgbouncer would throw an error on these statements it would prevent the invalid use in the first place.

**Comment by petere** [comment]
By design, PgBouncer does not look inside the packets that contain the commands that you send, so it cannot know this kind of thing. Changing this would require a major fundamental change and additional components such as an SQL parser.

Moreover, it is not guaranteed that PgBouncer is connecting a stock PostgreSQL client to a stock PostgreSQL server. The server could also be some other product that speaks the PostgreSQL protocol. So we can't know exactly what the commands coming through actually mean.

A possible way to address this issue might be to build a plugin for the PostgreSQL backend and catch the forbidden commands there.

**Comment by takeda** [comment]
I see, that makes sense.
