### ISSUE TITLE
Question: Build 1.12.0 doesn't allow the options -regservice and -unregservice anymore when self-built on Windows

### ISSUE THREAD

**Issue by SeppPenner** [pgbouncer/pgbouncer#474]
I found out that version 1.12.0 built for Windows on my own doesn't provide the `-regservice` and `-unregservice` options anymore as stated in the readme under https://github.com/pgbouncer/pgbouncer#running-on-windows.

![image](https://user-images.githubusercontent.com/9639361/77068753-6456e680-69e7-11ea-8b94-d07024ad8354.png)

Is this intended and if yes how should pgbouncer be started (as service) now?

**Comment by SeppPenner** [comment]
More info: I used pgbouncer-1.12.0.tar.gz for building.

**Comment by petere** [comment]
It seems that your build is somehow wrong because it doesn't show the Windows-specific options. For testing, I threw a `pgbouncer -h` command at the end of the Windows build on AppVeyor, and it works correctly (https://ci.appveyor.com/project/petere/pgbouncer/build/job/4o9cvou07e5kgd8j#L457), so it's not completely broken. Please check how you made your build. Are you cross-compiling by any chance?

**Comment by SeppPenner** [comment]
I'm not sure. I have used `pgbouncer-1.12.0.tar.gz` from the releases for building and did this:

1. Unzip the release to a folder, e.g. `C:\PGBouncerForBuilding` and go to this directory.
2. Run the following commands:

    ```bash
    cd pgbouncer-1.12.0 # Adjust this if your release is different.
    ./autogen.sh
    ./configure ...
    make
    make install
    ```

Is there something I understood wrong with this? Is `pgbouncer-1.12.0.tar.gz` a release for Linux only?

**Comment by petere** [comment]
In general, it should work on Windows. The AppVeyor CI build shows that it works. Obviously, there are lots of details that could go wrong.

If you are using the release tarball, then you shouldn't have to run `autogen.sh` because all that stuff is already in the tarball. Probably not related, though.

**Comment by SeppPenner** [comment]
> In general, it should work on Windows. The AppVeyor CI build shows that it works. Obviously, there are lots of details that could go wrong.

Yes, I've seen that. There must be still some error in my setup. I will check that

> If you are using the release tarball, then you shouldn't have to run autogen.sh because all that stuff is already in the tarball. Probably not related, though.

Ah ok. Good to know :)
