### ISSUE TITLE
Accessing temporary table in client2 with pgbouncer throwing error table is not exist

### ISSUE THREAD

**Issue by balukrishnans** [pgbouncer/pgbouncer#513]
Hi,
I need to use the temporary table feature in PostgreSQL.
The temporary table that is automatically dropped at the end of a DB session, so I tested that with pgbouncer to maintain the session.
```
Client1 creates a temp table T1.
Client1 tries to access temp table T1.
Client2 tries to access temp table T1.
```
But while Client2 tries to access the temp table T1 it throws the error 'T1' does not exist.
`PG Bouncer is working in "session mode"`

**Comment by eulerto** [comment]
It does not even work with Postgres and therefore it won't work with pgbouncer + Postgres.

Although, I said it does not work, there is a setup that it works. `pool_size = 1` guarantees that client 2 gets the same connection client 1 put back into the pool and `server_reset_query =` that does not execute `DISCARD` (or any other command that cleans the temporary table). Of course, client 2 should connect before pgbouncer closes that backend because it is idle for some time. I'm **not** advising you to use such a setup; it is a hack. Instead, use an unlogged table or even a regular table.

**Comment by petere** [comment]
As we discussed on the Gitter chat also, this isn't an issue in PgBouncer.
