### ISSUE TITLE
Should pgbouncer really be logging so much by default?

### ISSUE THREAD

**Issue by gityerhubhere** [pgbouncer/pgbouncer#56]
By default:
log_connections = 1
log_disconnections = 1

This means that the log file is absolutely filled up with enormous amounts of data in no time. Should this really be? Why not only log errors by default? That is the only thing you're normally interested in, no? Not every single connect/disconnect to the pool? In fact, the latter should only be an extreme oddball debug case or something, don't you agree?

**Comment by markokr** [comment]
Yeah, on real usage you may want to disable it.  But it might help newbies who dont know pgbouncer that well.

I don't want to have any new features on by default that impact performance, even if they help newbies.  Because it will give bad experience to people upgrading pgbouncer.

But the connection logging has been enabled by default for long time, so I think we should just keep it that way.
