### ISSUE TITLE
Will pgbouncer re-read user's credentials form the userlist.txt

### ISSUE THREAD

**Issue by melaraj2** [pgbouncer/pgbouncer#580]
We are running PGBouncer in AWS ECS.  We would like to implement IAM authentication.  The way that works is that you can call an AWS CLI command to retrieve a password to access the Postgres database.  This password is good for just 15 minutes, so a new password must be obtained before the 15 minutes expire. I have two questions:

1.) Does PGBouncer read the userlist.txt file each time it makes a connection, or will it only read it once during startup?  
2.) If the credentials change for an already open connection, will the connection dropped by the server, or will it work indefinitely?

I will maintain the userlist.txt current with a valid password in a separate process, as long as the pgBouncer looks for the password there on each connection attempt.

**Comment by eulerto** [comment]
PgBouncer reads authentication file (`auth_file`) as soon as it is modified (this condition is checked 3x per second -- see [do_full_maint](https://github.com/pgbouncer/pgbouncer/blob/master/src/janitor.c#L668)). If you turn on verbose mode, you will see that every time you change the `auth_file` a new log message informs that the file was loaded again.

PgBouncer doesn't close connections whose database credentials were changed. Indeed, PgBouncer doesn't know that the database credentials changed.

Having said that you probably have a small window (max 1/3 second) that a new connection will failed because of wrong password. (I'm not considering the delay between the password is changed and it modifies the `auth_file`).
