### ISSUE TITLE
Ideal pgbench settings to test pgbouncer?

### ISSUE THREAD

**Issue by marklit** [pgbouncer/pgbouncer#671]
I've run the following against straight PG (TPS: 389) and pgbouncer (TPS: 305).

```
PGPASSWORD=test \
pgbench --host=127.0.0.1 \
        --port=6433 \
        --client=100 \
        --jobs=100 \
        --transactions=1000 \
        intel
```

I would expect a higher TPS from a pooler but straight PG beats pgbouncer out. I set up the initial db with `pgbench -i intel`. Am I missing something?

This is my pgbouncer config:

```
[databases]
intel = host=localhost port=5432 dbname=intel

[pgbouncer]
listen_port = 6433
listen_addr = localhost
auth_type = md5
auth_file = userlist.txt
logfile = pgbouncer.log
pidfile = pgbouncer.pid
admin_users = mark
max_client_conn = 100
default_pool_size = 100
```

**Comment by petere** [comment]
If you are just routing through pgbouncer to one database, then the TPS will probably be lower, since the processing inside pgbouncer takes a nonzero amount of time. I don't see how you can expect to get to a *higher* TPS in that setup. For that, you would need to route to multiple servers on the backend, perhaps. Also, it depends on whether the whole setup is CPU bound or I/O bound or network bound.

**Comment by marklit** [comment]
Okay, that's understood.
