### ISSUE TITLE
connection problem on an AWS RDS with pgbouncer

### ISSUE THREAD

**Issue by qdupuy** [pgbouncer/pgbouncer#787]
Hello,

I am trying to set up a pgbouncer to attack the RDS via my Kubernetes cluster, however this is encountering the following issues: 

```
2022-11-22 13:05:52.674 UTC [1] NOISE S-0x7fd3de9c7140: preprod_api/retool@10.0.110.221:5432 read pkt='R', len=24
2022-11-22 13:05:52.674 UTC [1] DEBUG S-0x7fd3de9c7140: preprod_api/retool@10.0.110.221:5432 calling login_answer
2022-11-22 13:05:52.674 UTC [1] DEBUG S-0x7fd3de9c7140: preprod_api/retool@10.0.110.221:5432 S: req SASL
2022-11-22 13:05:52.675 UTC [1] DEBUG S-0x7fd3de9c7140: preprod_api/retool@10.0.110.221:5432 S: SASL advertised mechanism: SCRAM-SHA-256
2022-11-22 13:05:52.675 UTC [1] ERROR S-0x7fd3de9c7140: preprod_api/retool@10.0.110.221:5432 cannot do SCRAM authentication: wrong password type
2022-11-22 13:05:52.675 UTC [1] LOG C-0x7fd3de9ce120: preprod_api/retool@10.0.50.86:12430 closing because: server login failed: wrong password type (age=0s)
2022-11-22 13:05:52.675 UTC [1] WARNING C-0x7fd3de9ce120: preprod_api/retool@10.0.50.86:12430 pooler error: server login failed: wrong password type
2022-11-22 13:05:52.675 UTC [1] LOG S-0x7fd3de9c7140: preprod_api/retool@10.0.110.221:5432 closing because: failed to answer authreq (age=0s)
```

Here is my pgbouncer configuration : 

```
/ $ cat /etc/pgbouncer/pgbouncer.ini
################## Auto generated ##################
[databases]
preprod_api = host=preprod.REDACTED.eu-west-3.rds.amazonaws.com port=5432 user=retool

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 5432
unix_socket_dir =
user = postgres
auth_file = /etc/pgbouncer/userlist.txt
auth_type = md5
auth_user = retool
pool_mode = session
ignore_startup_parameters = extra_float_digits

# Log settings
verbose = 2
admin_users = postgres,retool,nobody,pgbouncer
stats_users = postgres,retool,nobody,pgbouncer

# Connection sanity checks, timeouts
server_reset_query = DISCARD ALL

# TLS settings

# Dangerous timeouts
################## end file ##################
```

If I open a postgres-client, I've no problem.

The goal is to have a flow opening from outside without needing a gateway on the RDS.

**Comment by eulerto** [comment]
You didn't provide enough information. You should start with Postgres and PgBouncer versions. You should also provide the `password_encryption` setting in your `postgresql.conf`. Are you mixing password types in your Postgres cluster? Check `pg_authid` (Does RDS allow it?). You didn't mention what password types you are using in your `userlist.txt`. If you are using `SCRAM-SHA-256`, use it for both (Postgres and PgBouncer).

**Comment by galshmil** [comment]
Not sure if it's the same case, but I experienced the same behavior with users that were not configured with MD5 originally in the RDS when created.
When this happens, and you still try to access via MD5 password in `userlist.txt`, the authentication automatically falls back to try and use SCRAM (which causes the `wrong password type` massage).
Try creating a user with an MD5 configuration to begin with:
`CREATE ROLE md5test WITH LOGIN ENCRYPTED PASSWORD 'md5xxx';`

**Comment by durdina** [comment]
Hi all,
I've tried to triage this issue because I wanted to work on this problem. 

Unfortunately with the latest versions of RDS (I've tested both engines: RDS PostgreSQL 16.2 and Aurora PostgreSQL 16.1) I cannot reproduce the issue.

These are the configs I've tested:
|   | DB User name | DB User password encryption | PG Bouncer name | PG Bouncer password encryption | Status | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| psql@16 -> pgbouncer 1.22.1 -> RDS PostgreSQL 16.2 | test | scram-sha-256 | test | plain | Works |
| psql@16 -> pgbouncer 1.22.1 -> RDS PostgreSQL 16.2 | test | scram-sha-256 | test | scram-sha-256 | Cannot work ! |
| psql@16 -> pgbouncer 1.22.1 -> RDS Aurora PostgreSQL 16.1 | test | scram-sha-256 | test | plain | Works |
| psql@16 -> pgbouncer 1.22.1 -> RDS Aurora PostgreSQL 16.1 | test | scram-sha-256 | test | scram-sha-256 | Cannot work ! |

Useful commands:
`show password_encryption;` shows actual password encryption for new users
`CREATE EXTENSION rds_tools;  select * from rds_tools.role_password_encryption_type();`  shows whether a particular user uses md5 or scram-sha-256

These are my pgbouncer config snippets:
/usr/local/etc/pgbouncer/787/pbbouncer.ini
```
...
;; change to taste
auth_type = scram-sha-256 ;; (this can also be md5 - it won't make a difference)
;; probably need this
auth_file = /usr/local/etc/pgbouncer/787/userlist.txt
...
```
/usr/local/etc/pgbouncer/787/userlist.txt:
```
...
"test" "test"
;; SCRAM secret created from execution of "create role test login PASSWORD 'test'; select rolpassword from pg_authid where rolname = 'test';'
;; SCRAM secret for user 'test' created with help of local postgresql installation. It won't be useful though, as the salts are different. We need the real SCRAM secret from RDS :-(
;; Format: `SCRAM-SHA-256$<iteration count>:<salt>$<StoredKey>:<ServerKey>`
;;"test" "SCRAM-SHA-256$4096:Z+IBGiXWn6Ork4RooJ50xw==$KAN0fm7N63LYE4K927JO42Fz8fUf/mqIoukSRVlXTdE=:M1FU/Xys+17e+z8dLimw2SW7U7Z9E2F/3lTE6KAZh2Q="
...
```

Now why the combination of `scram-sha-256` in RDS and `scram-sha-256` secret stored in pgbouncer's `userlist.txt` does not work? Well, despite this option being supported by pgbouncer, it requires that the SCRAM secret in pgbouncer is THE SAME as the one store on server (in this case in AWS RDS). This restriction is documented [here](https://github.com/pgbouncer/pgbouncer/blob/34ab8180c9a0a8791bf1e122b07b857c8409f3aa/doc/config.md?plain=1#L1413-L1420) and it is an inherent requirement. PGBouncer cannot successfully authenticate to RDS PostgreSQL server when creating new connections if it does not know either a.) user password (in plan text) b.) SCRAM secret (mainly salt and number of iterations) that RDS used for given user. Unfortunately, RDS as managed environment,  does not allow access to this information for their DB users. Even under the most privileged user superuser (member of rds_superuser) the `select * from pg_authid; ` gives the `ERROR:  permission denied for table pg_authid`. That is a known behaviour and mentioned in this [official blog](https://aws.amazon.com/blogs/database/best-practices-for-migrating-postgresql-databases-to-amazon-rds-and-amazon-aurora/).

---

Now would this information help ?

@qdupuy : Is the issue still occurring (it's been some time since this ticket was opened)? Based on the logs from the client
```
2022-11-22 13:05:52.675 UTC [1] ERROR S-0x7fd3de9c7140: preprod_api/retool@10.0.110.221:5432 cannot do SCRAM authentication: wrong password type
```
I am suspecting that your userlist.txt contains the password for user 'retool' in md5 and not in plain text which is required if server uses SCRAM-SHA-256 password encryption for the user pgbouncer is connecting with. Or even more likely as per provided config snippet
```
auth_user = retool
```
because of this option being employed pgbouncer tries to issue `SELECT usename, passwd FROM pg_shadow WHERE usename=$1` however this select would inevitably get `ERROR:  permission denied for view pg_shadow` as access to this table (alias for pg_authid) is not something RDS supports. 

@galshmil : If pgbouncer only has MD5 password in userlist.txt, that might be a problem as the server expects scram-sha-256 and won't accept md5 password. PGbouncer has no way to authenticate using scram-sha-256 as it does not know the original password. For your case pgbouncer userlist.txt would need to be updated with password in plain text for the reasons I described above.

@ivankovnatsky : I am not sure how credentials rotation impacts RDS user credentials in this case. As per my knowledge with RDS the credentials can be rotated only if they are stored in AWS Secrets Manager (as opposed to being self-managed). This implies that the client (pgbouncer) in this case knows how to connect to AWS Secrets Manager to fetch the actual password valid at a time. Nevertheless from your description it seems that changing userlist.txt and replacing md5 password with plain text password helped. This is in line with the description I gave above. Presumably RDS for your user uses SCRAM-SHA-256 encryption and pgbouncer can only successfully authenticate it if it knows the password in plain form. 

--

If you guys can confirm above it would help to resolve the ticket.

If not and can still see the error, please specify more details such as DB user name, relevant lines from `pgbouncer.ini` ([databases]) and `userlist.txt`, psql command that you're using - one for direct connection to RDS and one for connection via pgbouncer. Then would be happy to try to reproduce it again.

Thanks,

**Comment by durdina** [comment]
**Technical notes**

In my previous comment I stated it is not possible to configure SCRAM secret in pgbouncer `userlist.txt` since this secret has to be the same as the one stored in managed server (RDS). RDS prohobits fetching the secret (or parts of it i.e. salt) for a particular user once it has been set. Although reading is prohibited, writing is not.

So configuring  scram-sha-256 on both sides is possible the other way around. It is possible to get the SCRAM secret pgbouncer has in the `userlist.txt` and overwrite the one stored in RDS via command:
```
alter role test password 'SCRAM-SHA-256$whather_the_secret_is;
```
If the value for password is in plain text, then alter role (or psql `\password` for that matter) computes the scram secret and sends that over the wire. However if the value supplied is the SCRAM secret itself it is submitted to server verbatim. Not sure whether this is officially supported (the documentation has no mention of this) but currently this works.

This opens a possibility to generate SCRAM secret for arbitrary password locally (using a custom script or even local postgres installation running on your desktop) and then taking the secret that has the format: `SCRAM-SHA-256$<iteration count>:<salt>$<StoredKey>:<ServerKey>` and setting it inside pgbouncer's `userlist.txt` as well as inside RDS via `alter role` command. I just tested it and it works.

**Comment by petere** [comment]
This is a good tip!

Yes, this is supported; see https://www.postgresql.org/docs/16/sql-createrole.html.

**Comment by JelteF** [comment]
Agreed very good tip. But to correct one thing: `\password` does **not** send the plaintext password over the wire. It actually uses this client side hashing trick to only send the SCRAM hash to the server.

**Comment by durdina** [comment]
Right, that's what I was trying to say with:
> If the value for password is in plain text, then alter role (or psql \password for that matter) computes the scram secret and sends that over the wire

But makes sense!

**Comment by JelteF** [comment]
Well ALTER ROLE doesn't send the scram secret over the wire, it actually sends the plain text password. Which is the main reason  `\password` exists: i.e. so the plain text password never gets to postgres so that logging and pg_stat_activity won't show it.
