### ISSUE TITLE
pg_isready succeeds on pgBouncer port even when target DB is down

### ISSUE THREAD

**Issue by DCCSKrezovic** [pgbouncer/pgbouncer#803]
I am running pgBouncer in Kubernetes and I implemented a readiness check where it simply calls "pg_isready" on the pgBouncer port

```
$ pg_isready -d postgres -h localhost -p 5432 -U pgbouncer
localhost:5432 - accepting connections
```

in the log I see:

```
2023-01-27 10:24:33.194 UTC [1] LOG C-0x702a3c88f080: (nodb)/pgbouncer@[::1]:48906 login attempt: db=postgres user=pgbouncer tls=TLSv1.3/TLS_AES_256_GCM_SHA384
```

There is nothing that indicates that target DB is down. Is it possible to add such check?

**Comment by petere** [comment]
What `pg_isready` does is only a subset of a full connection. It just gets to the point where the server requests authentication, but it does not actually proceed to log in. So in the context of pgbouncer, it cannot know whether the target database is up or not because it doesn't even fully log into pgbouncer.

I think `pg_isready` is not the right tool for what you are attempting.

**Comment by DCCSKrezovic** [comment]
Thanks for the hint. I think I can close this issue as not relevant for pgBouncer.
