### ISSUE TITLE
Pgbouncer can't resolve DB server name after system reboot.

### ISSUE THREAD

**Issue by ChCh27** [pgbouncer/pgbouncer#980]
I've built pgbouncer for use with Amazon Linux 2023. After a system reboot, pgbouncer is unable to resolve the postgres server's name. Manually restarting pgbouncer resolves the issue. It seems highly likely that pgbouncer reads resolv.conf before it gets modified by the DHCP client and doesn't re-read it later.

I found a solution for this issue:
Replace the "After" parameter in the User section of the pgbouncer.service file from 'network.target' to 'network-online.target'. This resolves the problem.

**Comment by JelteF** [comment]
Are you compiling with the `--with-cares` flag? That's the DNS resolver library with the least amount of bugs (as the readme also explains).

**Comment by ChCh27** [comment]
@JelteF Yes. I've tried with cares and evdns . Result is the same in both cases.

**Comment by eulerto** [comment]
DNS setup is done one during the initialization and cannot be changed (see `dns_setup`). If the network is not online when the OS decides to start PgBouncer, you will have a DNS resolution issue. A few months ago, rpm packaging changed from `network.service` to `network-online.service` [1] but deb doesn't [2]. Maybe we should do the same but I'm afraid it changes an important PgBouncer feature that is to hold client connections until Postgres is up and running. I'm saying that because according to `man 7 systemd.special` [3]:

```
Note the distinction between this unit and network.target. This unit is an active unit (i.e.
pulled in by the consumer rather than the provider of this functionality) and pulls in a service
which possibly adds substantial delays to further execution. In contrast, network.target is a
passive unit (i.e. pulled in by the provider of the functionality, rather than the consumer)
that usually does not delay execution much.
```

It could delay the service start up to $timeout (default is 90 seconds IIRC). PgBouncer will reject client connections if the network is not up. In the @ChCh27 scenario, it is worse because "fast" start might break DNS resolutions for the entire lifetime of the service. Even if we fix it (according to the libevent API [4] we could free and initialize the DNS resolver again but we need a mechanism to trigger it), it doesn't solve the OP problem because a human being or a robot needs to run a command to unbreak the DNS resolver. Any smart mechanism can potentially impose some overhead. Are we willing to add it?

[1] https://www.postgresql.org/message-id/e6d2c602-db46-0709-6519-ade189fa5203%40comcast.net
[2] https://salsa.debian.org/postgresql/postgresql-common/-/blob/master/systemd/system/postgresql%40.service
[3] https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
[4] https://libevent.org/doc/dns_8h.html

**Comment by petere** [comment]
The PostgreSQL documentation now also suggests `network-online.target` (see postgres/postgres@2d27e13b35). Maybe it's the better choice.
